### ISSUE TITLE
channel selection in FeatureView is broken

### ISSUE THREAD

**Issue by espenhgn** [CINPLA/phy-contrib#1]
Choosing a unit in ClusterView should select FeatureView channels according to channel/depth of the unit (that is, where the highest amplitude is found). Right now only ch. 0A/1A/0B/1B are used, independent of the channel/depth of the unit.

FeatureView/"Togge automated channel selection C" does nothing.

![image](https://user-images.githubusercontent.com/2492641/49722074-1f7cc580-fc64-11e8-9422-3a2b23faa9ce.png)

**Comment by lepmik** [comment]
That's not implemented yet, feel free to contribute.

Should be around here if I remember correctly: https://github.com/CINPLA/phy-contrib/blob/7d8094b7cf6c36b9d40376012f954bc83f0ff7d0/phycontrib/neo/gui.py#L171-L203

**Comment by espenhgn** [comment]
Looks like @alejoe91 already fixed this before xmas in commit b381237. I'll close this then.
