### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by malinroe** [CINPLA/phy-contrib#2]
KeyError: "No such object: 'timestamps' in path 'c:\\apps\\pilot_exp\\actions\\1009-281018-2\\data\\main.exdir\\processing\\electrophysiology\\channel_group_0\\FeatureExtraction'"

**Comment by espenhgn** [comment]
We fixed this now in https://github.com/CINPLA/phy-contrib/commit/72850ca26fd29998b994efeeb8d0ce75631eadc3
